### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly

### ISSUE THREAD

**Issue by rpatterson** [rpatterson/iiswsgi#5]
This error happens when using WebPI to install on full IIS, IOW when not using IIS Express and Web Matrix.  Here's the error from the logs:

```
DownloadManager Error: 0 : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Web.Deployment, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Web.Deployment, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Web.PlatformInstaller.MSDeployProxy.GetDeclaredParameters()
   at Microsoft.Web.PlatformInstaller.MSDeployPackage.get_DeclaredParameters()
   at Microsoft.Web.PlatformInstaller.UI.AppSitePage.GetApplicationName(MSDeployPackage package, String& appName)
   at Microsoft.Web.PlatformInstaller.UI.AppSitePage.InitializeComponent()
```

**Comment by rpatterson** [comment]
It can be worked around by installing the "Web Deploy Tool" in WebPI.  The [bdist_webpi](https://github.com/rpatterson/iiswsgi#build-webpi-feed-distribution) command works around this by adding it as a dependency for all MSDeploy packages.
